apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: sdyoo/db:mysql_1 # 한글화 해서 패키지 한 DB
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: rootpass
            - name: MYSQL_DATABASE 
              value: frodo
            - name: MYSQL_USER # database에 권한이 있는 user
              value: frodo
            - name: MYSQL_ROOT_HOST # 접근 호스트
              value: '%'  
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: userpass
          ports:
            - containerPort: 3306
              name: mysql